"""
frontend/backend/email_notifier.py
------------------------------------
Sends email alerts to the admin when system metrics breach
WARNING or CRITICAL thresholds set by the user.

Uses Python's built-in smtplib — no extra dependencies.
Supports Gmail (with App Password), Outlook, or any SMTP server.

Config via environment variables in log_generator/.env:

    ALERT_EMAIL_FROM      = your-sender@gmail.com
    ALERT_EMAIL_PASSWORD  = your-app-password
    ALERT_EMAIL_TO        = admin@yourcompany.com
    ALERT_SMTP_HOST       = smtp.gmail.com          (default)
    ALERT_SMTP_PORT       = 587                     (default)

    # Cooldown: min seconds between emails for the same severity
    # Prevents flooding if metrics stay high for a long time
    ALERT_COOLDOWN_SECONDS = 300                    (default 5 min)

Gmail setup:
    1. Enable 2FA on your Google account
    2. Go to Google Account → Security → App Passwords
    3. Create an App Password for "Mail"
    4. Use that 16-char password as ALERT_EMAIL_PASSWORD
"""

import os
import smtplib
import threading
from email.mime.text    import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime           import datetime
from dotenv             import load_dotenv
from pathlib            import Path

# Resolve .env
_ENV_PATH = (
    Path(__file__).resolve()
    .parent.parent.parent
    / "log_generator" / ".env"
)
load_dotenv(dotenv_path=_ENV_PATH)

# ── Config ────────────────────────────────────────────────────────────────────
EMAIL_FROM        = os.getenv("ALERT_EMAIL_FROM",       "")
EMAIL_PASSWORD    = os.getenv("ALERT_EMAIL_PASSWORD",   "")
EMAIL_TO          = os.getenv("ALERT_EMAIL_TO",         "")
SMTP_HOST         = os.getenv("ALERT_SMTP_HOST",        "smtp.gmail.com")
SMTP_PORT         = int(os.getenv("ALERT_SMTP_PORT",    "587"))
COOLDOWN_SECONDS  = int(os.getenv("ALERT_COOLDOWN_SECONDS", "300"))


class EmailNotifier:
    """
    Thread-safe email notifier with per-severity cooldown.
    Cooldown prevents repeated emails if metrics stay breached.
    """

    def __init__(self):
        self._lock          = threading.Lock()
        self._last_sent: dict[str, datetime] = {}   # severity → last sent time
        self._enabled       = self._check_config()

    def _check_config(self) -> bool:
        if not EMAIL_FROM or not EMAIL_PASSWORD or not EMAIL_TO:
            print(
                "⚠️  Email alerts disabled — set ALERT_EMAIL_FROM, "
                "ALERT_EMAIL_PASSWORD, ALERT_EMAIL_TO in log_generator/.env"
            )
            return False
        print(
            f"✅ Email alerts enabled → {EMAIL_TO}  "
            f"(cooldown: {COOLDOWN_SECONDS}s)"
        )
        return True

    def _is_on_cooldown(self, severity: str) -> bool:
        last = self._last_sent.get(severity)
        if last is None:
            return False
        elapsed = (datetime.now() - last).total_seconds()
        return elapsed < COOLDOWN_SECONDS

    def _build_email(
        self,
        severity:   str,
        metrics:    dict,
        exceeded:   list[str],
        threshold_info: dict,
    ) -> MIMEMultipart:
        """Builds a clean plain-text + HTML email."""

        ts        = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        icon      = "⚠️" if severity == "WARNING" else "🔴"
        color_hex = "#facc15" if severity == "WARNING" else "#f87171"
        subject   = f"{icon} AIOps {severity}: System metric threshold breached"

        # ── Plain text ────────────────────────────────────────────────────────
        plain = f"""
AIOps Incident Detection — {severity} Alert
============================================
Time      : {ts}
Severity  : {severity}

Current Metric Values
---------------------
  CPU Usage    : {metrics.get('cpu', '—'):.2f}%
  Memory Usage : {metrics.get('memory', '—'):.2f}%
  Disk Usage   : {metrics.get('disk', '—'):.2f}%

Thresholds Breached
-------------------
{chr(10).join(f'  • {e}' for e in exceeded)}

Configured Limits
-----------------
{chr(10).join(f'  {k}: {v}%' for k, v in threshold_info.items() if v is not None)}

Action Required
---------------
Please investigate the system immediately.
This alert was generated by the AIOps LSTM Autoencoder Incident Detection System.

-- AIOps Dashboard
"""

        # ── HTML ──────────────────────────────────────────────────────────────
        exceeded_rows = "".join(
            f"<tr><td style='padding:4px 12px;color:#f87171;'>⚠ {e}</td></tr>"
            for e in exceeded
        )
        limit_rows = "".join(
            f"<tr><td style='padding:2px 12px;color:#888;font-size:12px;'>{k}</td>"
            f"<td style='padding:2px 12px;color:#e8e8e8;font-size:12px;'>{v}%</td></tr>"
            for k, v in threshold_info.items() if v is not None
        )

        html = f"""
<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#0e0e0e;font-family:'IBM Plex Mono',monospace;color:#e8e8e8;">
  <div style="max-width:560px;margin:32px auto;background:#161616;border:1px solid #2a2a2a;border-radius:6px;overflow:hidden;">

    <!-- Header -->
    <div style="background:{color_hex}15;border-bottom:2px solid {color_hex};padding:20px 24px;">
      <div style="font-size:11px;letter-spacing:0.1em;color:#888;margin-bottom:4px;">AIOPS INCIDENT DETECTION</div>
      <div style="font-size:22px;font-weight:600;color:{color_hex};">{icon} {severity} ALERT</div>
      <div style="font-size:11px;color:#888;margin-top:4px;">{ts}</div>
    </div>

    <!-- Metrics -->
    <div style="padding:20px 24px;border-bottom:1px solid #2a2a2a;">
      <div style="font-size:10px;letter-spacing:0.08em;color:#555;margin-bottom:12px;">CURRENT METRIC VALUES</div>
      <table style="width:100%;border-collapse:collapse;">
        <tr>
          <td style="padding:6px 0;color:#a78bfa;font-size:13px;">CPU Usage</td>
          <td style="padding:6px 0;text-align:right;font-size:18px;font-weight:600;color:#a78bfa;">{metrics.get('cpu', 0):.2f}%</td>
        </tr>
        <tr>
          <td style="padding:6px 0;color:#38bdf8;font-size:13px;">Memory Usage</td>
          <td style="padding:6px 0;text-align:right;font-size:18px;font-weight:600;color:#38bdf8;">{metrics.get('memory', 0):.2f}%</td>
        </tr>
        <tr>
          <td style="padding:6px 0;color:#fb923c;font-size:13px;">Disk Usage</td>
          <td style="padding:6px 0;text-align:right;font-size:18px;font-weight:600;color:#fb923c;">{metrics.get('disk', 0):.2f}%</td>
        </tr>
      </table>
    </div>

    <!-- Breached thresholds -->
    <div style="padding:20px 24px;border-bottom:1px solid #2a2a2a;">
      <div style="font-size:10px;letter-spacing:0.08em;color:#555;margin-bottom:10px;">THRESHOLDS BREACHED</div>
      <table style="width:100%;border-collapse:collapse;">
        {exceeded_rows}
      </table>
    </div>

    <!-- Configured limits -->
    <div style="padding:16px 24px;border-bottom:1px solid #2a2a2a;">
      <div style="font-size:10px;letter-spacing:0.08em;color:#555;margin-bottom:8px;">CONFIGURED LIMITS</div>
      <table style="width:100%;border-collapse:collapse;">
        {limit_rows}
      </table>
    </div>

    <!-- Footer -->
    <div style="padding:14px 24px;background:#111;font-size:10px;color:#555;text-align:center;">
      AIOps LSTM Autoencoder · Incident Detection System
    </div>
  </div>
</body>
</html>
"""

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = f"AIOps Alert <{EMAIL_FROM}>"
        msg["To"]      = EMAIL_TO
        msg.attach(MIMEText(plain, "plain"))
        msg.attach(MIMEText(html,  "html"))
        return msg

    def _send_async(self, msg: MIMEMultipart, severity: str):
        """Sends email in a background thread — never blocks the SSE stream."""
        def _send():
            try:
                with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                    server.ehlo()
                    server.starttls()
                    server.login(EMAIL_FROM, EMAIL_PASSWORD)
                    server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())
                print(f"📧 Alert email sent → {EMAIL_TO}  [{severity}]")
            except smtplib.SMTPAuthenticationError:
                print("❌ Email auth failed — check ALERT_EMAIL_FROM / ALERT_EMAIL_PASSWORD")
            except smtplib.SMTPException as e:
                print(f"❌ SMTP error: {e}")
            except Exception as e:
                print(f"❌ Email send error: {e}")

        t = threading.Thread(target=_send, daemon=True)
        t.start()

    def notify(
        self,
        severity:       str,
        metrics:        dict,
        exceeded:       list[str],
        threshold_info: dict,
    ):
        """
        Public method — call this from the SSE stream whenever
        a WARNING or CRITICAL is detected.

        Args:
            severity       : "WARNING" or "CRITICAL"
            metrics        : { cpu, memory, disk } current values
            exceeded       : list of human-readable breach descriptions
            threshold_info : { 'CPU Warning': 70, 'CPU Critical': 85, ... }
        """
        if not self._enabled:
            return
        if severity not in ("WARNING", "CRITICAL"):
            return

        with self._lock:
            if self._is_on_cooldown(severity):
                remaining = COOLDOWN_SECONDS - (
                    datetime.now() - self._last_sent[severity]
                ).total_seconds()
                print(
                    f"📧 Email cooldown active for {severity} "
                    f"— {remaining:.0f}s remaining"
                )
                return

            self._last_sent[severity] = datetime.now()

        msg = self._build_email(severity, metrics, exceeded, threshold_info)
        self._send_async(msg, severity)

    @property
    def enabled(self) -> bool:
        return self._enabled

    def reset_cooldown(self):
        """Call this if you want to force the next alert to send immediately."""
        with self._lock:
            self._last_sent.clear()


# Singleton — import and use this instance throughout the backend
notifier = EmailNotifier()